name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        scssfiles: [one, two]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ matrix.scssfiles }}.scss
